[package]
name = "vrchat-avatar-menu"
version = "0.1.0"
edition = "2021"
authors = ["Zoe <zoe@zyoh.ca>"]

[dependencies]
vrchat_osc = { git = "https://github.com/Zyoh/Rust-VRChat-OSC" }
rosc = "0.9.1"
egui = "0.20.1"
eframe = "0.20.1"
rfd = "0.11.0"
regex = "1.7.1"
